name: Build branch

on:
  push:
    branches:
      - main
    paths:
      -  'pom.xml'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v4.0.1
